# Generated by Django 5.0.3 on 2024-03-07 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)])),
                ('contexto', models.CharField(max_length=300)),
                ('pergunta', models.CharField(max_length=300)),
                ('letra_a', models.CharField(max_length=300)),
                ('letra_b', models.CharField(max_length=300)),
                ('letra_c', models.CharField(max_length=300)),
                ('letra_d', models.CharField(max_length=300)),
                ('letra_e', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=1)),
                ('imagens', models.ImageField(blank=True, null=True, upload_to='img_questoes')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='questao.area')),
            ],
        ),
    ]
